# Generated by Django 3.2.9 on 2021-12-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
