# Generated by Django 3.2.9 on 2021-12-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='question_1',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Why did you come up with this project? What pushed you to thus idea?'),
        ),
    ]
