# Generated by Django 3.2.9 on 2021-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211219_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='static/images/brand.jpg', null=True, upload_to=''),
        ),
    ]
